apiVersion: v1
kind: Service
metadata:
  name: devops4-service
spec:
  type: NodePort
  selector:
    app: devops4
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 32140
      protocol: TCP
